services:
  postgres:
    image: postgres:16.3-bullseye
    container_name: workspace-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: workspace-postgres
